### Dormir ###
bed:
  can-sleep: true

### Eventos de bloques ###
spawn-on-break:
  diamond-ore:
    chance: 15.0
    amount: 1
    mobs:
      - CREEPER
      - LIGHTNING_BOLT
  stones:
    chance: 1.0
    amount: 1
    mobs:
      - SILVERFISH
  beenest:
    chance: 75.0
    amount: 3
    mobs:
      - BEE
  coal-ore:
    chance: 0.0
    amount: 0

### Eventos de mobs ###
entity:
  ##### Al Morir #####
  death:
    evoker:
      # Spawnea un Illusioner
      chance: 100.0
      amount: 1
    zombies:
      explosion:
        chance: 45.0
        power: 1.5
        break-blocks: true
    blaze:
      # Spawnea un Breeze
      chance: 100.0


  ###### Al ser golpeadas #####
  hurt:
    chicken:
      chance: 50.0
      amount: 3
      mobs:
        - CREEPER
        - LIGHTNING_BOLT

    cow:
      chance: 100
      amount: 1
      mobs:
        - EVOKER_FANGS

    pig: # Manda a volar a jugadores
      chance: 100.0

    bee: # Invoca x abejas con un mob sobre ella
      chance: 100.0
      amount: 1
      mob: WITHER_SKELETON # Mob subido

    axolotl:
      chance: 100.0
      amount: 2
      mobs:
        - VEX

    rabbit:
      chance: 100.0
      amount: 5 # TNT_MINECART

    sheep:
      chance: 30.0
      mob: SPIDER

    turtle:
      chance: 100.0 # Veneno

    llama-wanderingt:
      chance: 100.0 # Slow


    ## MOBS HOSTILES ##
    enderman:
      chance: 100.0 # Nausea

    spiders:
      chance: 50.0 # Darkness

    skeletons:
      enable-teleport: true

    creeper: # Al ser golpeados por una flecha
      speed: true

    phantom:
      projectile-inmune: true


  ##### Al interactuar #####
  interact:
    cow:
      fly: true


  ##### Al disparar proyectiles ####
  shoot:
    skeleton:
      chance: 25.0 # Slow

  ##### Al spawnear #####
  spawn:
    phantom:
      resistance: true
      chance: 100.0 # Chance de resis + mob
      mob: SKELETON

    brute:
      speed:
        enable: true
        amplifier: 1

    ravager:
      speed:
        enable: true
        amplifier: 1

    zombies:
      baby:
        chance: 25.0
        speed: false
      horse-mounted:
        chance: 25.0


### Eventos especiales ###

special:
  player-targeted:
    creeper:
      enable: true

    enderman:
      enable: true


## ////////test//////// ##
frozen:
  multipliers:
    speed: 1.0
    jump: 1.0
    swim: 1.0 # max 10

    health: 1.0
    def: 1.0
    knb-res: 1.0 # max 10

    atk: 1.0
    atk-spd: 1.0
    atk-knb: 1.0 # max 5
    follow-range: 1.0 # max 2

    size: 1.0

cold:
  multipliers:
    speed: 1.0
    jump: 1.0
    swim: 1.0 # max 10

    health: 1.0
    def: 1.0
    knb-res: 1.0 # max 10

    atk: 1.0
    atk-spd: 1.0
    atk-knb: 1.0 # max 5
    follow-range: 1.0 # max 2

    size: 1.0

warm:
  multipliers:
    speed: 1.0
    jump: 1.0
    swim: 1.0 # max 10

    health: 1.0
    def: 1.0
    knb-res: 1.0 # max 10

    atk: 1.0
    atk-spd: 1.0
    atk-knb: 1.0 # max 5
    follow-range: 1.0 # max 2

    size: 1.0

hot:
  multipliers:
    speed: 1.0
    jump: 1.0
    swim: 1.0 # max 10

    health: 1.0
    def: 1.0
    knb-res: 1.0 # max 10

    atk: 1.0
    atk-spd: 1.0
    atk-knb: 1.0 # max 5
    follow-range: 1.0 # max 2

    size: 1.0

veryhot:
  multipliers:
    speed: 1.0
    jump: 1.0
    swim: 1.0 # max 10

    health: 1.0
    def: 1.0
    knb-res: 1.0 # max 10

    atk: 1.0
    atk-spd: 1.0
    atk-knb: 1.0 # max 5
    follow-range: 1.0 # max 2

    size: 1.0
