name: MyPlugin
version: '${project.version}'
main: me.faksho.pandoraProject.MyPlugin
api-version: '1.17'

#TODO ver que hacer con esto xddd
# Commands
commands:
  die:
    description: Te vas a morir cabron
    usage: /<command>
  god:
    description: UwU
    aliases:
      - mododelpapu
  feed:
    description: Dejas el hambre atrás
    aliases:
      - chavitotengohambre
